name: Pr verify

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  pr_verify:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate diff
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Get changed files
      id: get_changed_files
      run: |
        # get the list of changed folders
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] || [[ "${{ github.event_name }}" == "push" ]] ; then
          # For workflow_dispatch or push, include all folders except .github
          CHANGED_FOLDERS=$(git ls-tree -d --name-only HEAD | grep -v '.github' | sort -u)
        else
          CHANGED_FOLDERS=$(git diff --name-only origin/main ${{ github.head_ref }} | grep -oE '^[^/]+/' | sort -u)
        fi

        echo "CHANGED_FOLDERS=$CHANGED_FOLDERS" >> "$GITHUB_ENV"

    - name: Set up Go
      uses: actions/setup-go@v4
      if: env.CHANGED_FOLDERS != ''
      with:
        go-version: '1.22'

    - name: Install Dagger CLI
      if: env.CHANGED_FOLDERS != ''
      run: |
        curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.18.6 sh
        sudo mv bin/dagger /usr/local/bin/

    - name: Run Unit Tests
      if: env.CHANGED_FOLDERS != ''
      run: |
        for dir in $CHANGED_FOLDERS; do
          echo "Running tests in $dir"
          cd $dir
          if [ -f go.mod ]; then
            dagger develop # set up module
            dagger functions # ensures dagger can show the module functions
            dagger run go test -v ./
          elif [ -f requirements.txt ]; then
            dagger develop # set up module
            dagger functions # ensures dagger can show the module functions
            dagger run python -m unittest discover -s . -v
          elif [ -f package.json ]; then
            dagger develop # set up module
            dagger functions # ensures dagger can show the module functions
            dagger run npm test
          else
            echo "No tests found in $dir"
          fi
          cd -
        done
