name: Pr verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pr_verify:
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install Dagger CLI
      run: |
        curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.16.1 sh
        sudo mv bin/dagger /usr/local/bin/

    - name: Run Unit Tests
      run: |
        for dir in $(find . -name 'go.mod' -not -path './.github/*' -exec dirname {} \;); do
          echo "Running tests in $dir"
          cd $dir
          dagger develop # set up module
          dagger functions # ensures dagger can show the module functions
          dagger run go test -v ./
          cd - 
        done
